# Generated by Django 4.1.1 on 2022-10-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_username', models.CharField(max_length=122)),
                ('entered_password', models.EmailField(max_length=122)),
                ('entered_email', models.CharField(max_length=12)),
                ('entered_mobileno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='print_hello.register')),
            ],
        ),
    ]
