# Generated by Django 4.1.1 on 2022-10-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newuserregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('password', models.EmailField(max_length=122)),
                ('email', models.CharField(max_length=12)),
                ('firstname', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
